# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qsc_food', '0005_auto_20171115_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portion',
            new_name='Partition',
        ),
    ]
