# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsc_food', '0006_auto_20171116_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fibre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
